name: CI
on:
  push:
    branches:
      - test
jobs:
  Test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: test
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
      - name: Run tests
        run: mvn -s .github/maven-ci-settings.xml clean verify -B
